spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
